### PR TITLE
Add pow

### PR DESCRIPTION
**Pull request by hdgarrood**
Is this the right place for this?

### CODE REVIEW

**Comment by hdgarrood** [comment]
I was thinking it might also be nice to add a `pow :: forall a. (Semiring a) => a -> Int -> a` which takes advantage of associativity so that `pow x n` only needs to apply `mul` `log2 n` times, but I'm not sure where that should go.

**Comment by hdgarrood** [comment]
Oh actually I guess `Prelude` would probably be the most sensible place, and we could implement it using the FFI?

**Comment by hdgarrood** [comment]
Or maybe it should go in `monoid`, and actually be `pow :: forall a. (Monoid a) => a -> Int -> a`, although we might have to treat negative powers as 0.

**Comment by paf31** [comment]
I would like to see this added to `monoids`, but it's probably good to have a specialized version here too, without the type class overhead.

**Comment by hdgarrood** [comment]
Cool, do you think this is good to merge then?

**Comment by paf31** [comment]
It looks good to me!

**Comment by hdgarrood** [comment]
Thanks :)

**Pull request merged**
