### PR TITLE
Add Field Parity instance, resolves #30

### LINKED ISSUE #30: Monoid Parity instance?
I would like to suggest that we define the following instances:

```purescript
instance semigroupParity :: Semigroup Parity where
  append Even Even = Even
  append Even Odd = Odd
  append Odd Even = Odd
  append Odd Odd = Even

instance monoidParity :: Monoid Parity where
  mempty = Even

-- I guess this would need to go in a separate library, since groups aren't defined in core afaik
instance groupParity :: Group Parity where
  ginverse = id
```

(as a group, `Parity` would be isomorphic to the group ℤ/2ℤ).

A nice consequence of doing this would be that `parity :: Int -> Parity` becomes a group homomorphism, where the group over `Int` we are considering is the additive one. That is,

```purescript
parity x <> parity y = parity (x + y)
```

holds for all `x, y :: Int`. Additionally, the function `parity :: Sym -> Parity` in my [symmetric-groups](https://github.com/hdgarrood/purescript-symmetric-groups) library, where `Sym` is the type of permutations on the set `{1,2,...n}` for some (finite) n, would also become a group homomorphism.

### PR DESCRIPTION
**Pull request by hdgarrood**
Also add a note about the Ord instance, since there are two possible Ord
instances.

### CODE REVIEW

**Comment by paf31** [comment]
👍 LGTM!

**Comment by hdgarrood** [comment]
Thanks! I just wanted to check before merging; we chatted about this in #27 and you pointed out that division on `Parity` might be a little surprising, since e.g. `Even / Even = Even`, even though the quotient of two even numbers is not necessarily even; and `Odd / Even = Odd`, even though the quotient of an odd and an even number is going to be neither even nor odd since it will not even be an integer... However, it's  only divisions by zero (=`Even`) which might be surprising, so maybe that's not so bad, since of course division by zero is undefined. The other two cases do work as expected; `Odd / Odd = Odd`, and `Even / Odd = Even`, which do both correspond to integer division properly (as long as the integers under consideration do divide into one another).

I still think these instances are quite nice to have, and that treating `Parity` as the field ℤ/2ℤ makes a lot of sense, especially since (if we are being precise) the two elements of ℤ/2ℤ are actually the sets of even and odd integers, rather than the integers 0 and 1. But I just wanted to check again before merging this too hastily, since we came to the opposite conclusion before.

**Comment by paf31** [comment]
I'm happy with that explanation of it in terms of division by zero - that makes sense. Sorry for this taking so long, let's merge :)

**Comment by hdgarrood** [comment]
No worries at all!

**Pull request merged**
